---

- hosts: all
  become: true
  tasks:

  - name: update repository
    apt:
      update_cache: yes

  - name: install cpu-checker package
    apt:
      name: cpu-checker
      state: latest

  - name: install flatpak support
    apt:
      name: flatpak
      state: latest

  - name: install flatpak support
    apt:
      name: plasma-discover-backend-flatpak
      state: latest